name: FlaskTodo2 CI Test

on:
  push:
    braches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version

      - name: Run Test with Docker Compose
        run: |
          docker compose up --build --abort-on-container-exit --exit-code-from tets
          docker compose down
 
